version: '2'
services:
  nginx:
    image: nginx:alpine
    restart: always 
    volumes:
      - ./public:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - neco_link
networks:
  neco_link:
    external: true 

